/* Generated By:JavaCC: Do not edit this line. BeerCompilerTreeConstants.java Version 5.0 */
package parser;

public interface BeerCompilerTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTCOMANDOS = 1;
  public int JJTCONDICIONAL = 2;
  public int JJTREPETICAO = 3;
  public int JJTFUNCAO = 4;
  public int JJTOPERACAO = 5;
  public int JJTEXPRESSAO = 6;
  public int JJTDECLARACAOVARIAVEL = 7;
  public int JJTTIPODADO = 8;
  public int JJTDADO = 9;
  public int JJTNUMERO = 10;
  public int JJTSTRING = 11;
  public int JJTBOOLEANO = 12;


  public String[] jjtNodeName = {
    "main",
    "comandos",
    "condicional",
    "repeticao",
    "funcao",
    "operacao",
    "expressao",
    "declaracaoVariavel",
    "tipoDado",
    "dado",
    "numero",
    "string",
    "booleano",
  };
}
/* JavaCC - OriginalChecksum=218e1aa8f74e22fbcc2737d6983120d8 (do not edit this line) */
