/* Generated By:JJTree&JavaCC: Do not edit this line. BeerCompilerConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BeerCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 5;
  /** RegularExpression Id. */
  int FIMPROGRAMA = 6;
  /** RegularExpression Id. */
  int INICIOBLOCO = 7;
  /** RegularExpression Id. */
  int FIMBLOCO = 8;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 9;
  /** RegularExpression Id. */
  int INTEIRO = 10;
  /** RegularExpression Id. */
  int REAL = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int ATRIBUICAO = 15;
  /** RegularExpression Id. */
  int SEPARADOR = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int PARESQ = 19;
  /** RegularExpression Id. */
  int ISTRING = 20;
  /** RegularExpression Id. */
  int PARDIR = 21;
  /** RegularExpression Id. */
  int CASADECIMAL = 22;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 23;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int FUNC = 28;
  /** RegularExpression Id. */
  int VERDADEIRO = 29;
  /** RegularExpression Id. */
  int FALSO = 30;
  /** RegularExpression Id. */
  int INTERRUPCAO = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int DIGITO = 33;
  /** RegularExpression Id. */
  int CARACTERE = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"geladeiraAberta\"",
    "\"geladeiraVazia\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"pilsen\"",
    "\"malzbier\"",
    "\"lager\"",
    "\"ipa\"",
    "\"helles\"",
    "\"=\"",
    "\",\"",
    "\"garrafa\"",
    "\"lata\"",
    "\"(\"",
    "\"\\\'\"",
    "\")\"",
    "\".\"",
    "<OPERADOR_ARITMETICO>",
    "<OPERADOR_LOGICO>",
    "\"rodizio\"",
    "\"in\"",
    "\"rodada\"",
    "<FUNC>",
    "\"cervejaGelada\"",
    "\"cervejaQuente\"",
    "\"chegaPorHoje\"",
    "<ID>",
    "<DIGITO>",
    "<CARACTERE>",
  };

}
